'use client';

import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import localFont from 'next/font/local';
import { usePathname } from 'next/navigation';
import { AppSidebar } from '../components/ui/app-sidebar';
import './globals.css';

const pretendard = localFont({
    src: './assets/fonts/PretendardVariable.woff2',
    display: 'swap',
    weight: '100 900',
    variable: '--font-pretendard',
});

/* TODO :: ThemeRegistry로 변경
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
*/

export default function RootLayout({ children }) {
    const pathname = usePathname();
    const path = pathname.split('/');
    const page = path.at(-1);
    const isHome = page == '';
    const isLogin = pathname.includes('login');

    return (
        <html
            lang="ko"
            className={`${pretendard.variable} h-full scroll-smooth text-text-pri font-medium min-h-full`}
        >
            <body className={`${pretendard.className} antialiased h-full`}>
                <div id="wrap" className="flex h-full">
                    <SidebarProvider>
                        <AppSidebar />
                        <main className="grow basis-0 flex flex-col" id="container">
                            <header className="h-[60px] fixed top-0 bg-blue-950 text-white flex flex-col justify-center px-4 w-full">
                                <div>헤더</div>
                            </header>
                            <div className="mt-[60px] p-8" id="contents-wrap">
                                {!isHome && !isLogin && <BreadCrumbs />}
                                <h2 className="text-2xl font-bold mb-4">페이지 타이틀</h2>
                                {children}
                            </div>
                            <footer className="bg-blue-950 text-white flex flex-col justify-center px-4 h-[40px] w-full mt-auto">
                                <div>Copyright 2025@ deserved</div>
                            </footer>
                        </main>
                        <SidebarTrigger />
                    </SidebarProvider>
                    {/* <aside className="w-[280px] h-full bg-pri">
                        <div className="h-[60px] bg-white"></div>
                    </aside> */}
                </div>
            </body>
        </html>
    );
}

{
    /* <Footer /> */
}

{
    /* <PageContainer title="예시">
                        {!isHome && !isLogin && <BreadCrumbs />}
                        {children}
                    </PageContainer> */
}
